name: authentication_repository
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  bloc: null
  dio: null
  equatable: ^2.0.5
  shared_preferences: null
  user_repository:
    path: ../user_repository

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
