# Generated by Django 3.1 on 2023-12-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='price',
            field=models.IntegerField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='images.category'),
        ),
    ]
