# Generated by Django 3.1 on 2023-12-27 21:35

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20231222_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=images.models.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
