# Generated by Django 3.1 on 2023-12-28 21:48

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20231228_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[images.models.validate_lowercase]),
        ),
    ]
