# Generated by Django 3.1 on 2023-12-29 20:11

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20231229_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutritive_benefits',
            field=models.CharField(help_text="Enter list separated with commas, end with a comma too ','", max_length=255, validators=[images.models.validate_comma]),
        ),
    ]
