name: user_repository
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
# path: ^1.8.0
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
